### ISSUE TITLE
if/then/else strict complaints about missing type "object"

### ISSUE THREAD

**Issue by akarasulu** [ajv-validator/ajv-cli#121]
So far, I'm really enjoying what Ajv can do, but I ran into a few complaints while using it on the CLI with conditional schemas using if/then/else. I created an example to reproduce the minor problem:

## Versions

 - "ajv": "^7.2.1",
 - "ajv-cli": "^4.2.0",
 - "ajv-formats": "^1.5.1",
 - "ajv-formats-draft2019": "^1.4.3",
 - "ajv-keywords": "^4.0.0",

## Example Foobar.json Schema

```yaml
$id: https://foobar.com/schema/1.0.0/Foobar.json
$schema: https://json-schema.org/draft/2019-09/schema#
title: Foobar
description: An example schema demonstrating the problem
type: object
required:
  - id
  - url
  - live
  - working
properties:
  id:
    type: number
  url:
    type: string
    format: iri
  live:
    type: boolean
  working:
    type: boolean
    if:
      properties:
        live:
          const: false
    then:
      properties:
        working:
          const: false
    else:
      properties:
        working:
          type: boolean
  workplace:
    if:
      properties:
        live:
          const: false
    then:
      properties:
        workplace:
          const: null
    else:
      properties:
        workplace:
          type: string
```

## Validation Output

```shell
❯ npx ajv --spec=draft2019 --validate-formats=true --verbose=true --all-errors=true -c ajv-keywords -c ajv-formats -c ajv-formats-draft2019 compile -s Foobar.yaml
strict mode: missing type "object" for keyword "properties" at "https://foobar.com/schema/1.0.0/Foobar.json#/properties/working/if" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://foobar.com/schema/1.0.0/Foobar.json#/properties/working/then" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://foobar.com/schema/1.0.0/Foobar.json#/properties/working/else" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://foobar.com/schema/1.0.0/Foobar.json#/properties/workplace/if" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://foobar.com/schema/1.0.0/Foobar.json#/properties/workplace/then" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://foobar.com/schema/1.0.0/Foobar.json#/properties/workplace/else" (strictTypes)
schema Foobar.yaml is valid
```

I did not expect these `strict mode: missing type "object" for keyword "properties" at ..` complaints.  Any idea what may be happening?

Thanks in advance,
Alex

**Comment by epoberezkin** [comment]
Please see strict-mode.md in ajv docs: https://ajv.js.org/strict-mode.html

**Comment by akarasulu** [comment]
Thanks, @epoberezkin, that clarified a lot.

For others seeing this, if you're getting `strictTypes` complaints you better double-check whether your schema is accurate. Turns out my schema was borked. Below is how to do it right, and not get those warnings:

```yaml
$id: https://foobar.com/schema/1.0.0/Foobar.json
$schema: https://json-schema.org/draft/2019-09/schema#
title: Foobar
description: An example schema demonstrating the problem
type: object
required:
  - id
  - url
  - live
properties:
  id:
    type: number
  url:
    type: string
    format: iri
  live:
    type: boolean
if:
  type: object
  properties:
    live:
      const: False
then:
  type: object
  properties:
    working:
      const: False
    workplace:
      const: null
else:
  type: object
  properties:
    working:
      type: boolean
    workplace:
      type: string
      nullable: True
```
